# Generated by Django 2.2.4 on 2019-12-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('salary', models.IntegerField()),
                ('dept', models.CharField(max_length=100)),
            ],
        ),
    ]
